ezsystems/ezplatform-solr-search-engine

- .travis.yml
Just checking if Travis triggers ok
> Added Travis configuration

- .travis.yml
- composer.json
- tests/SolrSearchEngine/Content/CriterionVisitor/FullTextTest.php
- tests/bootstrap.php
Trying to run integration tests from `ezpublish-kernel`.
> EZP-24619: Extract Solr: Run integration tests

- lib/eZ/Publish/Core/Search/Solr/Query/Content/CriterionVisitor/Ancestor.php
- lib/eZ/Publish/Core/Search/Solr/Query/Location/CriterionVisitor/Ancestor.php
- lib/eZ/Publish/Core/settings/search_engines/solr/criterion_visitors.yml
This PR resolves https://jira.ez.no/browse/EZP-24804
Review together with https://github.com/ezsystems/ezpublish-kernel/pull/1409
This implements `Ancestor` criterion visitors, accepting Location path string(s) as value.
> Implement EZP-24804: Ancestor criterion

- lib/eZ/Publish/Core/settings/tests/solr/multicore_dedicated.yml
- lib/eZ/Publish/Core/settings/tests/solr/multicore_shared.yml
- lib/eZ/Publish/Core/settings/tests/solr/single_core.yml
This configures searchable Url field type to enable tests.
> Implement EZP-24816: Indexable for Url field type

- lib/FieldValueMapper/GeoLocationMapper.php
- lib/Query/Content/CriterionVisitor/MapLocation/MapLocationDistanceIn.php
- lib/Query/Content/CriterionVisitor/MapLocation/MapLocationDistanceRange.php
JIRA: https://jira.ez.no/browse/EZP-25246
This fixes the exception caused by wrong float format when indexing content, also when searching.
> Fix EZP-25246 MapLocation issues with alternate locale

- .travis.yml
Disabled xdebug and memory limit when running composer.
> [travis] fixed php memory limit issues

- README.md
Added comment about commit and softcommit configurations in Solr.
> EZP-25788: Solr not indexing on content publish

- README.md
( See #43 for discussion on the settings themselves )
Review ping @pspanja @galileo @janit
> EZP-25788: Add example config for commit settings

- lib/Query/Content/CriterionVisitor/Field.php
- lib/Query/Content/CriterionVisitor/Field/FieldIn.php
- lib/Query/Content/CriterionVisitor/Field/FieldRange.php
- lib/Query/Content/CriterionVisitor/Field/FieldRelation.php
- lib/Query/Content/CriterionVisitor/FullText.php
- lib/Query/Content/CriterionVisitor/MapLocation.php
- lib/Query/Content/CriterionVisitor/MapLocation/MapLocationDistanceIn.php
- lib/Query/Content/CriterionVisitor/MapLocation/MapLocationDistanceRange.php
- lib/Resources/config/container/solr/criterion_visitors.yml
- tests/lib/Search/Query/CriterionVisitor/FullTextTest.php
Issue: https://jira.ez.no/browse/EZP-25309
~~Depends on https://github.com/ezsystems/ezpublish-kernel/pull/1655~~
> EZP-25309: Fix datetime value mapping

- .travis.yml
- composer.json
- lib/Query/Content/CriterionVisitor/FullText.php
- tests/lib/Search/Query/CriterionVisitor/FullTextTest.php
Resolves https://jira.ez.no/browse/EZP-26141
https://github.com/ezsystems/ezplatform-solr-search-engine/pull/63 reopened against `1.0` branch.
> EZP-26141: Search appears to conduct some form of 'OR' search not and 'AND' search

- lib/Query/Location/CriterionVisitor/Field/FieldRelation.php
- lib/Resources/config/container/solr/criterion_visitors.yml
This PR resolves https://jira.ez.no/browse/EZP-26756
Cherry-picked https://github.com/ezsystems/ezplatform-solr-search-engine/pull/69/commits/c7537d40afed88ff183c8460e1e9ab59665a76a2 from https://github.com/ezsystems/ezplatform-solr-search-engine/pull/69.
> EZP-26756: FieldRelation is not handled in Location search

- tests/lib/Resources/config/multicore_dedicated.yml
- tests/lib/Resources/config/multicore_shared.yml
- tests/lib/Resources/config/single_core.yml
Solr part of https://github.com/ezsystems/ezpublish-kernel/pull/1858
Only adjusted test config.
> EZP-26494: remove searchable TextBlock for tests

- .travis.yml
- README.md
- bin/.travis/init_solr.sh
> Issue: https://jira.ez.no/browse/EZP-26775
http://lucene.apache.org/solr/news.html#23-january-2017-apache-solrtm-640-available
http://lucene.apache.org/solr/news.html#6-february-2017-apache-solrtm-641-available
> EZP-26775: Update Solr 6 doc & test on Solr 6.4.1

- bundle/DependencyInjection/Configuration.php
- lib/Gateway/Endpoint.php
- tests/bundle/DependencyInjection/EzPublishEzPlatformSolrSearchEngineExtensionTest.php
- tests/lib/Search/Gateway/EndpointTest.php
> Issue: https://jira.ez.no/browse/EZP-27095
> EZP-27095: Parse Solr DSN setting at runtime

- README.md
Displays proper version number.
> Use Github for release badge

- lib/Resources/config/container/solr/criterion_visitors.yml
> Fix FieldLike criterion visitor service definition

- .travis.yml
- README.md
- bin/.travis/init_solr.sh
- bin/generate-solr-config.sh
This is is a small script that generates the solr config. 
This is particular useful if using Platform.sh has they require that config to be present in your source tree
Also, see https://github.com/ezsystems/ezplatform/pull/282
> EZEE-1903: Added bin/generate-solr-config.sh

- bundle/DependencyInjection/Configuration.php
> JIRA: -
Clarify info message for the `main_translations` config node.
> Clarify info message for the main_translations config node

- lib/Handler.php
| **JIRA issue**     | [EZP-30790](https://jira.ez.no/browse/EZP-30790)
| **Required by/Requires** | ezsystems/ezpublish-kernel#2714
| **New feature**    | no
| **Target version** | `master (2.0)` for eZ Platform `v3.0`
| **Tests pass**     | yes, failure is related to kernel dependency
| **Doc needed**     | no
This PR aligns the `\EzSystems\EzPlatformSolrSearchEngine\Handler::supports` method signature with ezsystems/ezpublish-kernel#2714 changes.
> EZP-30790: Aligned Search Handler supports method signature

- .travis.yml
Adding Slack notifications to this bundle.
Targets: 1.5, 1.7, 2.0, 3.0 and master
> [Travis] Add Slack notifications

- .travis.yml
- bin/.travis/init_solr.sh
> JIRA: -
Enabled Solr testing on 7.7.3 (last 7.X release) for 3.0 branch.
> Updated Solr to 7.7.3

- lib/Query/Common/QueryConverter/NativeQueryConverter.php
> JIRA: -
Bugfix / Improvment moved form ezcommerce-shop. See https://github.com/ezsystems/ezcommerce-shop/blob/f961ac36981cc8e393a35d4df688b455c41190c9/src/Siso/Bundle/SearchBundle/Service/Ezp/SisoSolrQueryConverter.php#L35
> Recursively merge facets params

- lib/Resources/config/container/solr/aggregation_result_extractors.yml
- lib/Resources/config/container/solr/aggregation_visitors.yml
- lib/ResultExtractor/AggregationResultExtractor/TermAggregationKeyMapper/AuthorAggregationKeyMapper.php
- tests/lib/Search/ResultExtractor/AggregationResultExtractor/TermAggregationKeyMapper/AuthorAggregationKeyMapperTest.php
> JIRA: https://jira.ez.no/browse/EZP-32045
Added support for AuthorTermAggregation. See ezsystems/ezplatform-kernel#120
> EZP-32045: Added support for AuthorTermAggregation

- lib/FieldMapper/ContentFieldMapper/ContentDocumentLocationFields.php
- lib/FieldMapper/LocationFieldMapper/LocationDocumentBaseFields.php
- lib/Query/Common/AggregationVisitor/SubtreeTermAggregationVisitor.php
- lib/Resources/config/container/solr/aggregation_result_extractors.yml
- lib/Resources/config/container/solr/aggregation_visitors.yml
- lib/ResultExtractor/AggregationResultExtractor/NestedAggregationResultExtractor.php
- lib/ResultExtractor/AggregationResultExtractor/TermAggregationKeyMapper/SubtreeAggregationKeyMapper.php
- lib/ResultExtractor/AggregationResultExtractor/TermAggregationResultExtractor.php
- tests/lib/Search/Query/Common/AggregationVisitor/SubtreeTermAggregationVisitorTest.php
- tests/lib/Search/ResultExtractor/AggregationResultExtractor/NestedAggregationResultExtractorTest.php
- tests/lib/Search/ResultExtractor/AggregationResultExtractor/TermAggregationKeyMapper/SubtreeAggregationKeyMapperTest.php
> JIRA: https://jira.ez.no/browse/EZP-32045
Added support for SubtreeTermAggregation. Depends on ezsystems/ezplatform-kernel#121
> EZP-32045: Added support for SubtreeTermAggregation

- .travis.yml
- bin/.travis/init_solr.sh
> JIRA: -
Backport of #187. **Please do not merge until integration tests pass.**
> Run integration tests on Solr 8.6.3 (for eZ Platform 2.5)

- lib/Query/Common/SortClauseVisitor/Score.php
- lib/Resources/config/container/solr/sort_clause_visitors.yml
> JIRA: https://jira.ez.no/browse/EZP-32107
Implemented visitor for `\eZ\Publish\API\Repository\Values\Content\Query\SortClause\Score` sort clause. See ezsystems/ezplatform-kernel#130
> EZP-32107: Impl. visitor for Score sort clause
