.travis.yml
bundle/EzPublishSolrSearchEngineBundle/DependencyInjection/Configuration.php
bundle/EzPublishSolrSearchEngineBundle/DependencyInjection/EzPublishSolrSearchEngineExtension.php
composer.json
lib/eZ/Publish/API/Repository/Tests/SetupFactory/LegacySolr.php
lib/eZ/Publish/Core/Search/Solr/Content/CriterionVisitor.php
lib/eZ/Publish/Core/Search/Solr/Content/CriterionVisitor/CustomField/CustomFieldIn.php
lib/eZ/Publish/Core/Search/Solr/Content/CriterionVisitor/Field/FieldIn.php
lib/eZ/Publish/Core/Search/Solr/Content/DocumentMapper.php
lib/eZ/Publish/Core/Search/Solr/Content/DocumentMapper/NativeDocumentMapper.php
lib/eZ/Publish/Core/Search/Solr/Content/Gateway/CoreFilter/NativeCoreFilter.php
lib/eZ/Publish/Core/Search/Solr/Content/Gateway/Native.php
lib/eZ/Publish/Core/Search/Solr/Content/Handler.php
lib/eZ/Publish/Core/Search/Solr/Content/Location/Handler.php
lib/eZ/Publish/Core/Search/Solr/Content/Location/SortClauseVisitor/Location/Id.php
lib/eZ/Publish/Core/Search/Solr/Content/Resources/schema.xml
lib/eZ/Publish/Core/settings/search_engines/solr.yml
lib/eZ/Publish/Core/settings/tests/solr/multicore_dedicated.yml
lib/eZ/Publish/Core/settings/tests/solr/multicore_shared.yml
tests/bundle/EzPublishSolrSearchEngineBundle/DependencyInjection/EzPublishSolrSearchEngineExtensionTest.php

This PR resolves https://jira.ez.no/browse/EZP-24649
See also: https://github.com/ezsystems/ezpublish-kernel/pull/1358
This implements indexing of Location documents as nested (block joined) documents of Content.
With that change the semantic configuration is simplified, and Location index is no longer separately configured.
Currently we don't support fulltext search with Location Search. Having Locations as nested documents of Content will enables us implementation of fulltext Location search using block join, for example:
```
{!child of=document_type_id:content v='<fulltext condition>'}
```
That means we don't have to include fulltext field in the Location documents, but can refer to the one in the (parent) Content document. Avoiding that means having better relevancy calculation. …

EZP-24649: Solr: Index Locations as nested documents of Content

---

lib/eZ/Publish/Core/Search/Solr/DocumentMapper/NativeDocumentMapper.php
lib/eZ/Publish/Core/Search/Solr/ResultExtractor.php
lib/eZ/Publish/Core/Search/Solr/ResultExtractor/LoadingResultExtractor.php
lib/eZ/Publish/Core/Search/Solr/ResultExtractor/NativeResultExtractor.php
lib/eZ/Publish/Core/settings/search_engines/solr.yml

> ##### This PR resolves https://jira.ez.no/browse/EZP-24704
> ##### Review together with https://github.com/ezsystems/ezpublish-kernel/pull/1372
This implements *native* result extractor, which extracts search result from data returned by Solr backend.
`NativeResultExtractor` replaces `LoadingResultExtractor`, which did the "extraction" by loading from persistence by ID returned from the Solr backend.
The motive is completely avoiding hitting of persistence when using `SearchService::findContentInfo()`.

EZP-24704: Solr: Implement native result extractor

---

lib/eZ/Publish/Core/Search/Solr/Query/Common/QueryConverter/NativeQueryConverter.php

Switching to eDisMax query parser.
eDisMax will provide a base for more potential functionality in the future, for example boost query.

Switch to eDisMax query parser

---

composer.json
lib/eZ/Publish/Core/Search/Solr/ResultExtractor.php

Review together with https://github.com/ezsystems/ezpublish-kernel/pull/1373
One of the remaining points from the workshop.
Initially the idea was for this to be plural (an array of strings), containing the array of matched language codes. Since we can't achieve that ATM the property is kept as string.

Renamed SearchHit::$contentTranslation to $matchedTranslation

---

lib/eZ/Publish/API/Repository/Tests/SetupFactory/LegacySolr.php
lib/eZ/Publish/Core/Search/Solr/Gateway.php
lib/eZ/Publish/Core/Search/Solr/Gateway/Native.php
lib/eZ/Publish/Core/Search/Solr/Handler.php

Review together with https://github.com/ezsystems/ezpublish-kernel/pull/1374
This replaces internal search handler method `setCommit()` with `refresh()`, which performs empty soft commit request.
Since indexing is by definition asynchronous/delayed, exposing this in API does not make much sense, since we can't know what exactly will/won't be committed at any given moment.
On the other hand, the method makes sense on the search handler level, which also exposes methods `indexContent()` and `indexLocation()` (these are not async).

Implement commit() instead of setCommit()

---

bundle/EzPublishSolrSearchEngineBundle/DependencyInjection/Configuration.php
bundle/EzPublishSolrSearchEngineBundle/DependencyInjection/EzPublishSolrSearchEngineExtension.php
tests/bundle/EzPublishSolrSearchEngineBundle/DependencyInjection/EzPublishSolrSearchEngineExtensionTest.php

This simplifies semantic configuration after https://github.com/ezsystems/ezplatform-solr-search-engine/pull/5
Indexing Locations as nested documents of Content removed the need for separate configuration for Location indexes. The configuration was removed, but the structure was not optimized.
Additionally `cluster` key is here renamed to `mapping`.
Previous full example:
```yaml
ez_search_engine_solr:
endpoints:
endpoint0:
dsn: http://localhost:8983/solr
core: core0
default_connection: solr_test
connections:
solr_test:
entry_endpoints:
- endpoint0
cluster:
content:
translations:
eng-GB: endpoint1
default: endpoint0
main_translations: endpoint0
```
New full example:
```yaml
ez_search_engine_solr:
endpoints:
endpoint0:
dsn: http://localhost:8983/solr
core: core0
default_connection: …
```

Simplify semantic configuration after nested Location documents

---

.travis.yml
composer.json
composer.lock

This makes possible to install the engine with latest ezpublish-kernel `master` and `5.4` stable.

Adjust ezsystems/ezpublish-kernel dependency

---

lib/eZ/Publish/Core/Search/Solr/Query/Content/CriterionVisitor/FullText.php
lib/eZ/Publish/Core/Search/Solr/Query/Location/CriterionVisitor/FullText.php
lib/eZ/Publish/Core/settings/search_engines/solr/criterion_visitors.yml
tests/lib/Search/Content/CriterionVisitor/FullTextTest.php

This PR resolves https://jira.ez.no/browse/EZP-24802
This implements full text Location search using child block join, possible since changing indexing of Locations to subdocuments of Content in https://jira.ez.no/browse/EZP-24649. The idea behind this was reusing parent document (Content) relevancy with full text Location search.
There is a bug in Solr version we currently support (`4.10`), causing skipping of scoring when using child block join: https://issues.apache.org/jira/browse/LUCENE-6588.
The issue is fixed since Solr `5.3` (latest).

Implement EZP-24802: Full text Location search

---

lib/eZ/Publish/Core/Search/Solr/DocumentMapper/NativeDocumentMapper.php
lib/eZ/Publish/Core/Search/Solr/FieldValueMapper/MultipleStringMapper.php
lib/eZ/Publish/Core/Search/Solr/FieldValueMapper/StringMapper.php
lib/eZ/Publish/Core/Search/Solr/Resources/language-fieldtypes.xml
lib/eZ/Publish/Core/Search/Solr/Resources/schema.xml

> #### This PR resolves https://jira.ez.no/browse/EZP-23247
> #### Review with https://github.com/ezsystems/ezpublish-kernel/pull/1418
This implements handling of the new SPI search backend field type `FullText`.
Fields of this type are not stored, but instead are copied to the real full text field `text`.
This is used by the field type's `Indexable` definitions for indexing full text data.
* removed handling of `DOMDocument` from string field value mapper (cleanup after merge of https://github.com/ezsystems/ezpublish-kernel/pull/262)
* referencing non-existent `HtmlField` SPI search backend field type

Implement EZP-23247: missing field type Indexable definitions

---

lib/eZ/Publish/Core/Search/Solr/DocumentMapper/NativeDocumentMapper.php

This PR resolves https://jira.ez.no/browse/EZP-24902
Review together with https://github.com/ezsystems/ezpublish-kernel/pull/1441
When mapping Content to documents per translation, translations are determined from the generated document fields. Since field is not mapped to the document if value of the field equals to `null`, it can happen that document is not added for the translation if all field values for the translation equal to `null`.
With this change a document will be indexed for translation even when it has no Content fields.
Additionally fixed indexing full-text fields to Location documents.

Fix EZP-24902: Document is not indexed for translation

---

bundle/DependencyInjection/EzSystemsEzPlatformSolrSearchEngineExtension.php

Endpoint class in bundle extension was forgotten in the restructuring.

Fixed EZP-24915: updated endpoint class constant

---

bundle/Command/SolrCreateIndexCommand.php

Registering Solr Search Engine bundle but forgetting configuration of the repository with `solr` search engine is likely to be one of the common mistakes, resulting in cryptic fatal error.
This updates indexing command with check for configured engine, throwing an exception with user friendly message if expected engine is not found.

Check for configured engine in the indexing command

---

lib/Query/Location/SortClauseVisitor/Location/Priority.php

Sort clauses content using `\eZ\Publish\API\Repository\Values\Content\Query\SortClause\Location\Priority` are ignored by Solr because `priority_id` doesn't exist.

Wrong solr field name for location priority

---

lib/FieldValueMapper/FloatMapper.php
lib/Query/CriterionVisitor.php

JIRA: https://jira.ez.no/browse/EZP-25187
Different locales can represet floats differently (such as `123,45` for `de_DE.UTF-8`), which cause solr indexing to fail.
This uses the same, simple solution adopted for ezfind's indexboost (https://github.com/ezsystems/ezfind/commit/f46a315f2fa117e7).

Fix EZP-25187: float/double indexing can fail due to locale

---

lib/Query/Content/CriterionVisitor/Field/FieldRelation.php
lib/Resources/config/container/solr/criterion_visitors.yml

JIRA: https://jira.ez.no/browse/EZP-25158
Attempting to use the `FieldRelation` Criterion will result in a "Intentionally not implemented" exception.
As the relation fields are already being indexed, the approach is to simply reuse/extend the Field criterion.

Fix EZP-25158: Missing FieldRelation Criterion visitor

---

.travis.yml
LICENSE
composer.json

To unblock #35:
- Bump requirements and version numbers
- tag kernel v6.0.1 and v6.1.1 with #35 enhancement, 6.0.x for testing on php 5.4 
- Add testing on PHP 7.0
- Switch to Travis Trusty environment for:
- Stable runs _(no more lost connection to solr issues)_
- More power _for faster integration runs_
- Improve how composer packages are installed _(prefer stable)_

v1.1 Bump and testing improvements 

---

lib/Gateway.php
lib/Gateway/Native.php
lib/Handler.php
lib/Query/Content/CriterionVisitor/CustomField/CustomFieldIn.php

Issue: https://jira.ez.no/browse/EZP-25792
> Status: Ready for review
> Depends on https://github.com/ezsystems/ezpublish-kernel/pull/1658 *(integration tests)*
Explanation: 
The problem is that when we delete location we also want to delete all related sub location with related content, but if there is a content that have still another existing location that is out of the delete location subtree we just need to reindex this location instead of delete it.
Solution:
The solution is to find first which location need to be reindexed and with then need to be deleted with the content. As solr is handling location that are within content block we need to reindex or delete content index data.

EZP-25792: Deleted location don't affect subitems

---

bundle/Command/SolrCreateIndexCommand.php
lib/Handler.php

**Related JIRA issue**: https://jira.ez.no/browse/EZP-25756
It fixes crashing of _ezplatform:solr_create_index_ command in 2 cases:

EZP-25756: Can't index data in solrBundle

---

lib/Resources/config/container/solr.yml
lib/Resources/config/container/solr/slots.yml

Another part of [EZP-25088](https://jira.ez.no/browse/EZP-25088)-related changes.
[Kernel PR #1704](https://github.com/ezsystems/ezpublish-kernel/pull/1704) moves search engines signal slot configuration to each search engine.
This PR implements it for Solr.

EZP-25088: Signal slots configuration for Solr search engine

---

bundle/EzSystemsEzPlatformSolrSearchEngineBundle.php
lib/Resources/config/container/solr/slots.yml
tests/lib/Resources/config/common.yml
tests/lib/Resources/config/multicore_dedicated.yml
tests/lib/Resources/config/multicore_shared.yml
tests/lib/Resources/config/single_core.yml
tests/lib/SetupFactory/LegacySetupFactory.php

This PR aligns with changes introduced in the [Kernel PR #1704](https://github.com/ezsystems/ezpublish-kernel/pull/1704), related to the JIRA issue [EZP-25088](https://jira.ez.no/browse/EZP-25088).
**Goal**: properly separate Solr search engine signal slots. Separating configuration is not enough as service names are overridden in case all search engine bundles are loaded in `AppKernel`
**Changes**:

EZP-25088: Align with signal slot dispatcher changes introduced by the Kernel PR #1704

---

lib/ResultExtractor.php

This is https://github.com/ezsystems/ezplatform-solr-search-engine/pull/52 reopened against `1.0`branch
This PR resolves https://jira.ez.no/browse/EZP-26123
This change allows mapping any type of facets as they come in facet_counts:  "facet_queries", "facet_fields", "facet_dates", "facet_ranges"  "facet_intervals"
This would be implementor's responsibility to map it properly, as the data structure is different.
For now, this is tested with visitors processing facet_fields and facet_intervals, if it gets positive feedback I can test if it's fine for other cases.

EZP-26123: Extract facets of all types

---

bundle/Resources/config/services.yml
lib/Resources/config/container/solr.yml
lib/Resources/config/container/solr/criterion_visitors.yml
lib/Resources/config/container/solr/facet_builder_visitors.yml
lib/Resources/config/container/solr/field_value_mappers.yml
lib/Resources/config/container/solr/services.yml
lib/Resources/config/container/solr/sort_clause_visitors.yml
phpunit.xml
tests/lib/Resources/config/multicore_dedicated.yml
tests/lib/Resources/config/multicore_shared.yml
tests/lib/Resources/config/single_core.yml

This is a backport of #58 to 1.0 branch, resolving JIRA Story: [EZP-26128](https://jira.ez.no/browse/EZP-26128).

EZP-26128: Backport to 1.0 deprecation warning fixes

---

lib/Resources/config/container/solr/slots.yml
tests/lib/Resources/config/common.yml

JIRA Story: [EZP-26128](https://jira.ez.no/browse/EZP-26128)
**TODO**:

EZP-26128: As a Developer I want deprecation issues resolved, so that application logs are clean

---

bundle/ApiLoader/SolrEngineFactory.php
bundle/Command/SolrCreateIndexCommand.php

Related to JIRA Story [EZP-26128](https://jira.ez.no/browse/EZP-26128).
I found more deprecated code which should be a part of #59. It's a backport to `1.0` as this code already existed there.
**TODO**:

EZP-26128: Remove more deprecated code

---

lib/Resources/config/container/solr/slots.yml

Should only be merged as is if https://github.com/ezsystems/ezpublish-kernel/commit/fae68bf1807d0a341c8612104723520ebc3d8fc1 becomes part of kernel 6.5.0, otherwise we'll need to hold this back until after SolrBundle 1.1.0, and bump kernel requirements to 6.5.1 for SolrBundle 1.1.1.

EZP-26186: Add solr configuration for new Slots added

---

bundle/Command/SolrCreateIndexCommand.php

JIRA: https://jira.ez.no/browse/EZP-26307
Problem: 
`bulk_count` parameter is cast to int without validation (converted to 0), while the loop would effectively index `$bulkCount+1` contents per run.
This would result in an infinite loop.
Fix by validating the parameter and indexing the correct number of contents.

Fix EZP-26307: incorrect bulk_count results in index loop

---

lib/Resources/config/container/solr/slots.yml

Status: **Ready for a review**
This PR aligns with Search Engine Slots introduced in the [Kernel PR #1776](https://github.com/ezsystems/ezpublish-kernel/pull/1776)
**TODO**:

EZP-26219: Add missing Search Engine slots

---

lib/DocumentMapper/NativeDocumentMapper.php
lib/FieldMapper/ContentFieldMapper/ContentDocumentBaseFields.php
lib/FieldMapper/ContentFieldMapper/ContentDocumentLocationFields.php
lib/FieldMapper/ContentTranslationFieldMapper/BlockDocumentsContentFields.php
lib/FieldMapper/ContentTranslationFieldMapper/BlockDocumentsMetaFields.php
lib/FieldMapper/ContentTranslationFieldMapper/ContentDocumentFulltextFields.php
lib/FieldMapper/LocationFieldMapper/LocationDocumentBaseFields.php
lib/FieldMapper/LocationFieldMapper/LocationDocumentContentFields.php
lib/Resources/config/container/solr.yml
lib/Resources/config/container/solr/field_mappers.yml

This PR resolves https://jira.ez.no/browse/EZP-26668
Following on https://jira.ez.no/browse/EZP-26368, this refactors `NativeDocumentMapper` implementation to use only field mappers to map document fields.
Duplication of internal methods in `ContentFieldMapper/ContentDocumentBaseFields` and `LocationFieldMapper/LocationDocumentContentFields` is intentional and temporary, since the followup to this is normalization of field names between Content and Location documents, which will enable replacing these with a common block document level field mapper.

EZP-26668: Index fields though field mapper plugins

---

lib/Indexer.php
lib/Resources/config/container/solr.yml
tests/lib/Resources/config/common.yml

> Related to: [EZP-26098](https://jira.ez.no/browse/EZP-26098).
This PR aligns with the most recent approach presented in the [Kernel PR #1738](https://github.com/ezsystems/ezpublish-kernel/pull/1738) implementing Search Engine Indexer Service for Solr, based on current version of `\EzSystems\EzPlatformSolrSearchEngineBundle\Command\SolrCreateIndexCommand`.
**TODO**:

EZP-26098: Implement Search Indexer Service

---

bundle/Command/SolrCreateIndexCommand.php

> Status: **Ready for a review**
This PR deprecates `ezplatform:solr_create_index` command in favor of the new `ezplatform:reindex` command.
**TODO**:

Deprecate ezplatform:solr_create_index command

---

lib/DocumentMapper/NativeDocumentMapper.php

This PR resolves https://jira.ez.no/browse/EZP-26707
This skips indexing full text data if the field is marked as not searchable (`FieldDefinitions::$isSearchable` property).
*Regular* fields are still indexed, since `isSearchable` is checked when resolving query for `Field` criterion/sort clause (and we're also going for `isSearchable` meaning only full text searchable).

EZP-26707: Search with Solr does not respect isSearchable setting of fields

---

.travis.yml

Workaround for the issue found in the stable image promoted on Dec 1, 2016.
See https://github.com/travis-ci/travis-ci/issues/6928#issuecomment-264227708

[Travis] Fix missing Java by using previous image

---

lib/CoreFilter/NativeCoreFilter.php
lib/Handler.php
lib/Query/Common/CriterionVisitor/LogicalAnd.php
lib/Query/Common/CriterionVisitor/LogicalOr.php
lib/Query/Common/CriterionVisitor/MatchNone.php
lib/Query/Common/QueryConverter/NativeQueryConverter.php

This PR resolves https://jira.ez.no/browse/EZP-26774
Counterpart on `ezpublish-kernel`: https://github.com/ezsystems/ezpublish-kernel/pull/1859
This switches used Solr query parameter from `q.alt` to `q`.
This is internal thing to the Solr backend, will enable using suggestions/spellchecking on the generated query.
Note: suggestions/spellchecking in this context is about handling it on the Solr backend side, not in the Solr search engine.
Related PR: https://github.com/ezsystems/ezplatform-solr-search-engine/pull/57
Also exposed and fixed:
- `MatchNone` visitor was not handled as subquery, which could result in unwanted pure negative query when used with other criteria
- removed unnecessary usage of `MatchAll` criterion
- refactored logical criteria visitors to avoid generating …

EZP-26774: switch from q.alt to q parameter to enable use of spellchecker in future version

---

lib/Query/Common/CriterionVisitor/Field.php
lib/Query/Content/CriterionVisitor/Field.php

Adds deprecated implementation for the abstract `Field` criterion visitor on the previous namespace.
See https://github.com/ezsystems/ezplatform-solr-search-engine/pull/72

Add deprecated implementation for BC reasons

---

.travis.yml
README.md
bin/.travis/init_solr.sh
lib/Resources/config/solr/language-fieldtypes.xml

This PR resolves https://jira.ez.no/browse/EZP-26775
`ezpublish-kernel` counterpart: https://github.com/ezsystems/ezpublish-kernel/pull/1864
This refactors Travis Solr initialization script and adds ability to test Solr `6.3.0`.
This is still standalone/multicore setup, no Solr Cloud testing is done. It would be possible to set that up, but the implementation requires some work before support for it would be sensible (we would be limited to 1 replica per shard).
From default full text field configuration `enablePositionIncrements` flag is removed as it's invalid with Solr v5+, and it was not used anyway since Solr v4.3.
See [Stop Filter documentation](https://cwiki.apache.org/confluence/display/solr/Filter+Descriptions#FilterDescriptions-StopFilter) for more details.

EZP-26775: supported Solr backend v6

---

.travis.yml

This reverts commit 2d6b6705d7775121276fdaf294c3fb00c185c9fd.
Should not be needed anymore.

Revert "[Travis] Fix missing Java by using previous image (#79)"

---

bundle/ApiLoader/BoostFactorProviderFactory.php
bundle/DependencyInjection/Configuration.php
bundle/DependencyInjection/EzSystemsEzPlatformSolrSearchEngineExtension.php
bundle/Resources/config/services.yml
composer.json
lib/FieldMapper/BoostFactorProvider.php
lib/FieldMapper/ContentTranslationFieldMapper/BlockDocumentsContentFields.php
lib/FieldMapper/ContentTranslationFieldMapper/ContentDocumentFulltextFields.php
lib/FieldMapper/ContentTranslationFieldMapper/ContentDocumentTranslatedContentNameField.php
lib/Gateway/Native.php
lib/Gateway/UpdateSerializer.php
lib/Query/Content/CriterionVisitor/FullText.php
lib/Resources/config/container/solr.yml
lib/Resources/config/container/solr/field_mappers.yml
lib/Resources/config/container/solr/services.yml
lib/Resources/config/solr/schema.xml
tests/bundle/DependencyInjection/EzPublishEzPlatformSolrSearchEngineExtensionTest.php
tests/lib/Search/FieldMapper/BoostFactorProviderTest.php
tests/lib/Search/Query/CriterionVisitor/FullTextTest.php

This implements index-time boost functionality, similar to the [one existing in eZ Find](https://github.com/ezsystems/ezfind/blob/master/settings/ezfind.ini#L215).
One problem found when implementing this was usage of [Solr's `copyField` directive](https://cwiki.apache.org/confluence/display/solr/Copying+Fields) to index full-text data to the `text` field. It was not possible to keep this, because in order for a field to have boost factor it must have [norms](https://cwiki.apache.org/confluence/display/solr/Field+Type+Definitions+and+Properties) (attribute `omitNorms="false"` in the schema). Field that has norms also must be indexed, which voids the whole approach with having non-indexed `*_fulltext` fields that are only copied to the destination `text` field.
For that reason `copyField` …

EZP-27227: Implement index-time boosting

---

lib/Container/Compiler/AggregateFacetBuilderVisitorPass.php
lib/Handler.php
lib/Query/Common/FacetBuilderVisitor/Aggregate.php
lib/Query/Common/FacetBuilderVisitor/ContentType.php
lib/Query/Common/FacetBuilderVisitor/Section.php
lib/Query/Common/FacetBuilderVisitor/User.php
lib/Query/Common/QueryConverter/NativeQueryConverter.php
lib/Query/FacetBuilderVisitor.php
lib/Query/FacetFieldVisitor.php
lib/Resources/config/container/solr/facet_builder_visitors.yml
lib/ResultExtractor.php
tests/lib/Container/Compiler/AggregateFacetBuilderVisitorPassTest.php

> Issue: https://jira.ez.no/browse/EZP-27327
> Epic: https://jira.ez.no/browse/EZP-26465
> Alternative to: #91*
Done:
- New logic for facet builder visitors with BC for existing once to be able to identify* which facets belongs to which facet builder, to be able to inject right facet builder when extracting the result from Solr:
- This makes ContentType and Section facets fully implemented _(for now)_ as we can now use `name` from the user provided value in FacetBuilder.
-  Improve User Facet handling to support all three sub types: `modifier`, `owner` and `group`
- Don't throw when encountering unsupported FacetBuilders, just ignore, user will have to iterate returned facets to generate his UI/app
- Enable the 3 facets _(User, ContentType, Section)_ supported atm also on Location search …

EZP-27327: Fix User / ContentType / Section facet support in Solr

---

lib/Resources/config/solr/schema.xml

JIRA issue: [https://jira.ez.no/browse/EZP-27724](https://jira.ez.no/browse/EZP-27724)
As described in issue, run Solr is impossible because in the newest version of Solr ``6.6.0`` field ``defaultSearchField`` is deprecated. 
This PR removes mentioned field from ``schema.xml``.
No changes in Solr behavior after deprecated field remove.
Second solution proposed here: https://github.com/ezsystems/ezplatform/pull/196
This PR is the same as https://github.com/ezsystems/ezplatform-solr-search-engine/pull/96 but with changed name and commit message.

EZP-27724: Remove Solr 6.6 deprecated schema field

---

lib/Resources/config/container/solr/slots.yml
lib/Slot/RemoveTranslation.php
tests/lib/Slot/RemoveTranslationTest.php
tests/lib/Slot/TestCase.php

Implements [EZP-27712](https://jira.ez.no/browse/EZP-27712) for Solr Bundle
----
This PR adds `RemoveTranslation` Search Engine Slot which reindexes Content on `RemoveTranslationSignal` introduced in ezsystems/ezpublish-kernel#2031
*Note: for ES/SQL Slot see ezsystems/ezpublish-kernel#2060.*
**TODO**:

EZP-27712: Enable RemoveTranslation Search Engine Slot

---

.travis.yml
README.md
bin/.travis/init_solr.sh

Context: Reports in https://jira.ez.no/browse/EZP-27647 from users that #90 broke solr4 setup with 1.7 release, so:
- Adding testing with kernel 6.7 just in case that might cause issues at some point _(in this case it was not relevant)_
- Add testing for newer version of Solr 6 while at it
- Update instructions for how to configure Solr 4 which seems to have gotten out of date in comparison with what we test as of #90

EZP-27647: Fix Solr 4 doc instructions

---

lib/Gateway/Endpoint.php

JIRA issue: https://jira.ez.no/browse/EZP-27774
As described in JIRA, the URL was built incorrectly (missing [at] sign) and `empty($this->username)` statement was wrong as well.
Futhermore, I have moved authorisation URL part `user:pass@` to the `getIdentifier()` method as this also has to be passed in `shards` URL parameter.

EZP-27774: Basic HTTP Authorisation fix

---

composer.json
tests/lib/Search/Query/CriterionVisitor/FullTextTest.php
tests/lib/Search/TestCase.php
tests/lib/Slot/TestCase.php

This PR resolves:
* upgrades PHPUnit to version 5.7
* removes deprecated  `getMock()` method
* upgrades `matthiasnoback/symfony-dependency-injection-test` to version 1.0
* adds bundle and lib test to `autoload-dev` section of Composer autoload

Enables PHPUnit v5

---

composer.json
tests/lib/SetupFactory/LegacySetupFactory.php

This PR fixes failures in CI tests for Solr run from `ezpublish-kernel` as a root-package.
Background story: The PR #102 splitted `autoload` settings into `autoload` and `autoload-dev`. 
This is fine when running tests from this package itself, however our `ezpublish-kernel` uses `SetupFactory` that exists in moved namespace prefix.
According to the [composer docs on `autoload-dev`](https://getcomposer.org/doc/04-schema.md#autoload-dev) this is `root-only` setting, so when Solr Bundle is required as a dependency, `composer dump-autoload` won't create proper paths.
**TODO**:

EZP-27916: [Integration tests] Make SetupFactory autoloaded in root packages

---

lib/Gateway/Native.php

> issue: https://jira.ez.no/browse/EZP-28005
This switches from `GET` to `POST` when requesting Solr `/select` endpoint.
In some cases very long queries are generated by the engine, hitting the server limit and causing errors. It can happen for example with complex user permissions or having lots of conditions on a field whose name is used in multiple ContentTypes.
While `GET` would be formally correct for `/select` resource, `POST` is more practical since it's size limit is higher. For example with Jetty `GET` is limited to 8k and `POST` to 200k.
Other than that it makes no difference for Solr and multiple projects already did the same for the same reason:
- https://github.com/lucidworks/banana/pull/159
- https://www.drupal.org/node/761990

EZP-28005: Use POST request for /select resource

---

composer.json
lib/Query/Common/QueryTranslator/Generator/WordVisitor.php
lib/Query/Common/QueryTranslator/WordVisitor.php
lib/Query/Content/CriterionVisitor/FullText.php
lib/Resources/config/container/solr.yml
lib/Resources/config/container/solr/criterion_visitors.yml
lib/Resources/config/container/solr/query_translator.yml
tests/lib/Search/Query/CriterionVisitor/FullTextTest.php

This resolves https://jira.ez.no/browse/EZP-26806
Related PR: https://github.com/ezsystems/ezpublish-kernel/pull/2101
This implements improved query syntax for FullText criterion.
Quick cheat sheet:
`word` `"phrase"` `(group)` `+mandatory` `-prohibited` `AND` `&&` `OR` `||` `NOT` `!`
Examples:
- grouping
```
one AND (two AND (three OR four))
```
- phrases
```
"this is a phrase" and these are words
```
- mandatory/prohibited operators (`+`, `-`)
```
+one two -three
```
And so on.
This is achieved through https://github.com/netgen/query-translator library, using `text` variant of the syntax it provides. The syntax can be customized by adjusting regular expressions used to tokenize the query input, meaning it can be easily adjusted if needed (for example using only the subset of the syntax, …

EZP-26806: Improve fulltext search query syntax

---

.php_cs

This PR aligns php-cs-fixer config with changes introduced by its recent update to `v2.7.1`.
Backporting to **1.0** as this branch is still supported by eZ Publish `5.x`.
**TODO**:

[CS] Aligned php-cs-fixer config with changes introduced by v2.7.1

---

lib/Gateway/HttpClient/Stream.php
lib/Resources/config/container/solr/services.yml

> issue: https://jira.ez.no/browse/EZP-28088
Note: This does not handle HTTP error codes returned, as code uses `ignore_errors`, however afaik what is relevant here is cases where we don't reach Solr _(network errors/dns/..)_. But if anyone see any other cases that would be relevant here please share :)
Also open question is if Solr would sometimes needs more time than 10s for handling calls, so might be timeout is too low here.
Todo:

EZP-28088: Re-try connections when trying to reach Solr

---

bundle/Command/SolrCreateIndexCommand.php
lib/Gateway/HttpClient/Stream.php
lib/Resources/config/container/solr/services.yml

> https://jira.ez.no/browse/EZP-28179
Backporting some of the features added to re-index command in [EZP-28176](https://jira.ez.no/browse/EZP-28176).
First and foremost `no-purge` and `since` options to be able to re-index only part of the index.

EZP-28179: [5.4] Support for selective indexing since date & no-purge

---

composer.json
lib/Indexer.php

> issue: https://jira.ez.no/browse/EZP-28176
> Depends on https://github.com/ezsystems/ezpublish-kernel/pull/2139
As a Developer I want a indexing command which is:
- faster at indexing (parallel indexing)
- able to refresh parts of index (by date or content id)
- able to omit purging so index is gradually refreshed on running prod setup
- able to remove index items if no longer existing (when I provide content id's to index)
Todo:

EZP-28176: Support for parallel and selective indexing command

---

lib/Gateway/EndpointRegistry.php
lib/Gateway/EndpointResolver.php
lib/Gateway/EndpointResolver/NativeEndpointResolver.php
lib/Gateway/Native.php
lib/Gateway/SingleEndpointResolver.php
lib/Resources/config/container/solr.yml
lib/ResultExtractor.php
lib/ResultExtractor/LoadingResultExtractor.php
tests/lib/Search/Gateway/EndpointResolver/NativeEndpointResolverTest.php

> Replaces #110 
> Attempt to fix usage on platform.sh where Solr does not know about dns of itself causing it to break
This is kind of working around the platform.sh dns issue _(solr service does not known about it's own dns)_, and it's only able to do it on single core, multi core is still broken on Platform.sh which means any serious multi language setup _(where you want to configure different language stemming rules and so on per core)_ will be blocked from using that.
- Platform.sh needs to fix their self discovery of their Solr setup, they anyway need that if people are to use multi / shared core setup.
- Far stretch, but might also be that this problem goes away if we enable solr cloud features, see pr on that.
/cc @vidarl

EZP-28814: Make single core Solr work on platform.sh

---

README.md

Matching the MaxTime of autoSoftCommit to 20ms. This value is recommeded in the documenetion.

Changing the  autoSoftCommit maxTime

---

.travis.yml
composer.json
tests/bootstrap.php
tests/lib/Resources/config/multicore_dedicated.yml
tests/lib/Resources/config/multicore_shared.yml
tests/lib/Resources/config/single_core.yml

| **JIRA issue**     | [EZP-29396](https://jira.ez.no/browse/EZP-29396)
| **Bug**| yes
| **Target version** | `1.5` and `master`
This change is required regarding changes done in kernel in: https://github.com/ezsystems/ezpublish-kernel/pull/2387.
Since test should be working properly with Redis, using of the `eZ\Publish\Core\Persistence\Cache\Tests\Helpers\IntegrationTestCacheServiceDecorator` is no longer necessary.

EZP-29396: Remove unnecessary test cache decorator

---

bin/.travis/init_solr.sh

Fixed regression in ezpublish-kernel tests, https://github.com/ezsystems/ezplatform-solr-search-engine/pull/120#pullrequestreview-144752341

[TRAVIS] Kernel tests fail due to wrong relative path to generate-solr-config.sh

---

lib/Query/Common/CriterionVisitor/Field/FieldIn.php
lib/Query/Common/CriterionVisitor/Field/FieldLike.php
lib/Query/CriterionVisitor.php

https://jira.ez.no/browse/EZP-29984
Adapt Solr Search Engine to correct support for LIKE with wildcards using "*".
Todo:

EZP-29984: Add support for Field LIKE criterion with "*" wildcards

---

composer.json
lib/Resources/config/container/solr/slots.yml

| **JIRA issue**     | [EZP-30136](https://jira.ez.no/browse/EZP-30136)
| **New feature**    | no
| **Target version** | `1.5`
This is part two of the fix for changes after updating content with `ezuser` field not being committed.
This PR depends on:
https://github.com/ezsystems/ezpublish-kernel/pull/2544

EZP-30136 - Updating content with "ezuser" field will not commit changes to Solr

---

composer.json

Current tagged kernel 6.7 is [6.7.9.1](https://github.com/ezsystems/ezpublish-kernel/releases/tag/v6.7.9.1) which does not contain changes required by https://github.com/ezsystems/ezplatform-solr-search-engine/commit/55558b70649a1c2a64be534c5c5e14dae8271c70
same for 6.13
This PR changes the requirement for kernel 6.7 to version 6.7.10 and kernel 6.13 to 6.13.6

Required kernel for eZ Platform 1.7 should be 6.7.10+

---

.travis.yml
bin/.travis/init_solr.sh
tests/lib/Resources/config/multicore_dedicated.yml

Target version: **1.5.x** for eZ Platform `1.7.x LTS`, `1.13.x LTS` and `7.x` FT.
This PR enables testing of:
This way we can cover all supported LTS versions and also test dedicated setup against the latest changes.
Note: dedicated multicore setup is about using single Solr core for single language.
TODO:

[Travis] Fixed test matrix to cover more Kernel versions when testing

---

.travis.yml
README.md
bin/.travis/init_solr.sh
composer.json

Story: https://jira.ez.no/browse/EZP-30169
Preparations for the 2.5LTS, to reduce test/support matrix to get rid of irrelevant versions _(by now)_.
Given location search scoring can never be supported on Solr 4 and given how old it is, it makes sense to stop using time on it for QA and others.

EZP-30169: Bump to 1.6 bundle version & drop Solr 4 support

---

lib/Resources/config/container/solr/slots.yml

>JIRA: https://jira.ez.no/browse/EZP-30139
>relevant PR: https://github.com/ezsystems/ezpublish-kernel/pull/2549
As hiding content reflects content children (by setting invisible flag on them), reindexing subtree is required.

EZP-30139: Add slots for hide/reveal content

---

bundle/ApiLoader/IndexingDepthProviderFactory.php
bundle/DependencyInjection/Configuration.php
bundle/DependencyInjection/EzSystemsEzPlatformSolrSearchEngineExtension.php
bundle/Resources/config/services.yml
lib/FieldMapper/ContentTranslationFieldMapper/ContentDocumentFulltextFields.php
lib/FieldMapper/IndexingDepthProvider.php
lib/Query/Content/CriterionVisitor/FullText.php
lib/Query/CriterionVisitor.php
lib/Resources/config/container/solr.yml
lib/Resources/config/container/solr/criterion_visitors.yml
lib/Resources/config/container/solr/field_mappers.yml
lib/Resources/config/container/solr/services.yml
tests/lib/Search/FieldMapper/IndexingDepthProviderTest.php
tests/lib/Search/Query/CriterionVisitor/FullTextTest.php

> JIRA: https://jira.ez.no/browse/EZP-30282
Impl. indexation of related objects for the full text search. 
Text of related content is stored in the `meta_related_content_X__text_t ` index fields where `X` is relation level e.g. `meta_related_content_1__text_t`, `meta_related_content_2__text_t ` 
As an User, I expect the following order of search results for query "Content A": `Content A`, `Content B`  when content repository contains `Content A` and  `Content B` with embedded `Content A`.
This is implemented by adding boost factor based on the following formula:
to the index fields with related content. Ref. 
https://github.com/ezsystems/ezplatform-solr-search-engine/blob/1238c57777b936c63a7b2d31a73032f8fee9e3c5/lib/Query/Content/CriterionVisitor/FullText.php#L154-L157
As a Developer, you …

EZP-30282: Impl. indexing of related objects for the full text search

---

.travis.yml
bundle/DependencyInjection/EzSystemsEzPlatformSolrSearchEngineExtension.php
composer.json
tests/bundle/DependencyInjection/EzPublishEzPlatformSolrSearchEngineExtensionTest.php
tests/lib/Container/Compiler/AggregateCriterionVisitorPassTest.php
tests/lib/Container/Compiler/AggregateFacetBuilderVisitorPassTest.php
tests/lib/Container/Compiler/AggregateSortClauseVisitorPassTest.php
tests/lib/Search/Gateway/EndpointResolver/NativeEndpointResolverTest.php
tests/lib/Search/Gateway/EndpointTest.php
tests/lib/Slot/RemoveTranslationTest.php

> JIRA: https://jira.ez.no/browse/EZP-30638

EZP-30638: Upgrade `ezsystems/ezplatform-solr-search-engine` to use Symfony 4 components

---

.travis.yml
bin/.travis/init_solr.sh
bundle/DependencyInjection/Configuration.php
bundle/DependencyInjection/EzSystemsEzPlatformSolrSearchEngineExtension.php
bundle/Resources/config/services.yml
lib/Gateway/DistributionStrategy.php
lib/Gateway/DistributionStrategy/AbstractDistributionStrategy.php
lib/Gateway/DistributionStrategy/CloudDistributionStrategy.php
lib/Gateway/DistributionStrategy/StandaloneDistributionStrategy.php
lib/Gateway/Native.php
lib/Resources/config/container/solr.yml
tests/lib/Resources/config/cloud.yml
tests/lib/Search/Gateway/DistributionStrategy/CloudDistributionStrategyTest.php
tests/lib/Search/Gateway/DistributionStrategy/StandaloneDistributionStrategyTest.php
tests/lib/SetupFactory/LegacySetupFactory.php

> JIRA: https://jira.ez.no/browse/EZP-30463
This PR introduces support for Solr Cloud. More information https://lucene.apache.org/solr/guide/6_6/solrcloud.html
From now on the user can specify data distribution strategy for connection via `distribution_strategy` option. The possible values are: 
* `standalone` - https://lucene.apache.org/solr/guide/6_6/legacy-scaling-and-distribution.html (current implementation)
* `cloud` - Solr Cloud 
The default value is `standalone` for backward compatibility reasons. 
Example Solr Cloud configuration :
```yml
ez_search_engine_solr:
endpoints:
main:
dsn: '%solr_dsn%'
core: '%solr_main_core%' 
en:
dsn: '%solr_dsn%'
core: '%solr_en_core%'
fr:
dsn: '%solr_dsn%'
core: '%solr_fr_core%'
connections:
default:
distribution_strategy: cloud
entry_endpoints:
- …
```

EZP-30463: As an Developer, I want to use Solr Cloud

---

lib/Query/Content/CriterionVisitor/Factory/FullTextFactory.php
lib/Resources/config/container/solr/criterion_visitors.yml

|     |      |
| --- | --- |
| Bug | yes
| Target version | `v2.0 (master)` for eZ Platform `v3.0`
| Required by | ezpublish-kernel, ezplatform-richtext to unblock failing Solr integration tests.
Symfony 4 no longer allows using private services in DIC `@=service` expressions so we need to provide
factory instead.
**TODO:**

[SF4] Implemented factory for IndexingDepthProvider

---

lib/Query/Common/SortClauseVisitor/Random.php
lib/Resources/config/container/solr/sort_clause_visitors.yml
lib/Resources/config/solr/schema.xml

| **JIRA issue**     | [EZP-28898](https://jira.ez.no/browse/EZP-28898)
| **Requires** | ezsystems/ezpublish-kernel#2605
| **Bug/Improvement**| no
| **New feature**    | yes
| **Target version** | Solr Bundle `2.0` for eZ Platform `3.0`
| **Tests pass**     | yes
| **Doc needed**     | yes
This allows random sorting based on a seed.  Using the same seed will result in same order of random results.
Example:
This example rotates the used seed based on time so the returned results have a new order every 360 seconds.
```
$query = new Query();
$query->sortClauses = [
new Random((int)(time() / 360)),
];
```

EZP-28898: Implemented SortClause visitor for Random sort

---

bundle/DependencyInjection/Configuration.php

> JIRA: https://jira.ez.no/browse/EZP-30846
Since Symfony 4.3 configuration root name should be passed via constructor instead of using "Symfony\Component\Config\Definition\Builder\TreeBuilder::root()" method.
More information:
* https://symfony.com/blog/new-in-symfony-4-2-important-deprecations#deprecated-tree-builders-without-root-nodes
* https://github.com/symfony/symfony/blob/master/UPGRADE-4.2.md#config

EZP-30846: Dropped deprecated Symfony\Component\Config\Definition\Builder\TreeBuilder::root method calls

---

.travis.yml

Adjusted the minimum requirements for ezpublish-kernel on Travis to the values present in composer.json (https://github.com/ezsystems/ezplatform-solr-search-engine/blob/1.5/composer.json#L15) to avoid memory errors like this one: https://travis-ci.org/ezsystems/ezplatform-solr-search-engine/jobs/588966737

[Travis] Bumped minimum required ezpublish-kernel versions for tests

---

composer.json

Updated branch-alias for dev-master to 2.0.x in composer.json according to #136:
Due to the major changes in Solr, support for 7.X will be part of the ezplatform-solr-search-engine 2.0 release which will be compatible with eZ Platform 2.5 release. Solr 6.X will be dropped in this release.
Solr 7.X and Solr 8.X will be officialy supported in ezplatform-solr-search-engine 3.0 release which will be compatible with eZ Platform 3.X.

[composer] Set branch alias to 2.0.x-dev

---

composer.json

Updated branch-alias for dev-master to `3.0.x` in `composer.json` according to https://github.com/ezsystems/ezplatform-solr-search-engine/pull/136:
> Due to the major changes in Solr, support for 7.X will be part of the ezplatform-solr-search-engine 2.0 release which will be compatible with eZ Platform 2.5 release. Solr 6.X will be dropped in this release.
>
> Solr 7.X and Solr 8.X will be officialy supported in ezplatform-solr-search-engine 3.0 release which will be compatible with eZ Platform 3.X.

[composer] Set branch alias to 3.0.x-dev

---

composer.json
lib/Handler.php

JIRA ticket: https://jira.ez.no/browse/EZP-30296
Bulk deleting using `deleteByQuery` has been introduced. I couldn't find particular information about Solr's bulk operation size limit, at least not in their documentation, but I think it's good to have some limit to prevent exceeding GET length limit for instance.
After a talk with @andrerom and @alongosz I decided to move further work on slots to a separated PR. Therefore, this one covers only bulk deleting.

EZP-30296: Large API subtree delete leads to serious Solr index inconsistencies

---

.travis.yml
bin/.travis/init_solr.sh
bin/generate-solr-config.sh
lib/Query/Common/QueryConverter/NativeQueryConverter.php
lib/Resources/config/solr/schema.xml

> JIRA: https://jira.ez.no/browse/EZP-30835
https://issues.apache.org/jira/browse/SOLR-11501:
> Starting a query string with local-params {!myparser ...} is used to switch the
query parser to another, and is intended for use by Solr system developers, not end users doing searches. To reduce negative side-effects of unintended hack-ability, we've limited the cases that local-params will be parsed to only contexts in which the default parser is "lucene" or "func". So if defType=edismax then q={!myparser ...} won't work. In that example, put the desired query parser into defType. Another example is if deftype=edismax then hl.q={!myparser ...} won't work for the same reason. In that example, either put the desired query parser into hl.qparser or set hl.qparser=lucene. Most users won't run …

EZP-30835: Added support for Solr 7.7

---

lib/Resources/config/solr/schema.xml

> JIRA: -
Fixed resolved conflicts in `schema.xml` during https://github.com/ezsystems/ezplatform-solr-search-engine/pull/136 merge up.  
* duplicated definition of the `random` field type. The second occurrence is here: 
https://github.com/ezsystems/ezplatform-solr-search-engine/blob/8587f3e3b261fd3dcc9269d6de84eda862798540/lib/Resources/config/solr/schema.xml#L133
* leftover currency field type definition (dropped in https://github.com/ezsystems/ezplatform-solr-search-engine/commit/da9056d5a31ff7d4ecb01690ed53b2981854e2b8#diff-2ef3da3ce7e2d13c93a0e1a4742c06c5L57)

Fixed duplicated random field type definition in schema.xml

---

composer.json

The requirement for `ezpublish-kernel` in `composer.json` is wrongly set for `7.5.7@dev`, as the next kernel released required will be `7.5.6` (eZ Platform 2.5.6 was released with kernel `7.5.5`).
This PR changes requirement to `^7.5.6@dev`

Fixed wrong kernel version in composer.json

---

bundle/Command/SolrCreateIndexCommand.php
lib/Container/Compiler/CoreFilterRegistryPass.php
lib/Container/Compiler/EndpointRegistryPass.php
lib/Container/Compiler/GatewayRegistryPass.php
lib/Gateway/EndpointRegistry.php
lib/Gateway/EndpointResolver/NativeEndpointResolver.php
lib/Handler.php
lib/Query/Common/CriterionVisitor/Field/FieldIn.php
lib/Query/Common/CriterionVisitor/Field/FieldLike.php
lib/Query/Common/CriterionVisitor/Field/FieldRange.php
lib/Query/Common/CriterionVisitor/Field/FieldRelation.php
lib/Query/Common/CriterionVisitor/MapLocation/MapLocationDistanceIn.php
lib/Query/Common/CriterionVisitor/MapLocation/MapLocationDistanceRange.php
lib/Query/Common/SortClauseVisitor/Field.php
lib/Query/Common/SortClauseVisitor/MapLocationDistance.php
lib/Query/FacetBuilderVisitor.php

[EZP-31021](https://jira.ez.no/browse/EZP-31021)
Main PR: https://github.com/ezsystems/ezpublish-kernel/pull/2878

EZP-31021: Revised exception and command messages

---

lib/Resources/config/container/solr/field_mappers.yml

The empty field was indexed only for Contents (not Locations), therefore it was impossible to use IsEmpty Criterion when searching for locations.
This PR changes tag for `EzSystems\EzPlatformSolrSearchEngine\FieldMapper\ContentTranslationFieldMapper\ContentDocumentEmptyFields` to `ezpublish.search.solr.field_mapper.block_translation` so empty fields will be indexed also for Locations.
After applying the fix `php bin/console ezplatform:reindex` has to be executed to create indexes containing empty fields for locations.
More in JIRA ticket: https://jira.ez.no/browse/EZP-31275

EZP-31275: Fixed wrong tag for ContentDocumentEmptyFields

---

lib/Query/Common/CriterionVisitor/ContentTypeIdentifierIn.php
lib/Resources/config/container/solr/criterion_visitors.yml

> https://jira.ez.no/browse/EZP-31127
Variant of https://github.com/ezsystems/ezpublish-kernel/pull/2872 PR for Solr

EZP-31127: Skipped non-existing Content Types in ContentTypeIdentifier criterion

---

lib/Query/Common/CriterionVisitor/Factory/FullTextFactoryAbstract.php
lib/Query/Content/CriterionVisitor/Factory/ContentFullTextFactory.php
lib/Query/Content/CriterionVisitor/Factory/FullTextFactory.php
lib/Query/Location/CriterionVisitor/Factory/LocationFullTextFactory.php
lib/Resources/config/container/solr/criterion_visitors.yml
tests/lib/Resources/config/cloud.yml
tests/lib/Resources/config/common.yml
tests/lib/Resources/config/multicore_dedicated.yml
tests/lib/Resources/config/multicore_shared.yml
tests/lib/Resources/config/single_core.yml
tests/lib/Search/Query/Content/CriterionVisitor/FullTextTest.php

| **JIRA issue**     | [EZP-31226](https://jira.ez.no/browse/EZP-31226)
| **New feature**    | no
| **Target version** | `1.7` for bug fixes or improvements _(on existing features)_
| **Tests pass**     | [yes](https://travis-ci.org/ezsystems/ezplatform-solr-search-engine/builds/642365366)
| **Doc needed**     | no
Solution for reported bug:
https://jira.ez.no/browse/EZP-31226
Fixed missing "depth" parameters and added new test for fulltext search for embed content
Changes also in ezpublish-kernel: https://github.com/ezsystems/ezpublish-kernel/pull/2922
**TODO**:

EZP-31226: Added MaxDepth parameter for query location criterion and set default max depth=2 for integration tests

---

lib/Resources/config/container/solr/slots.yml

This PR depends on: https://github.com/ezsystems/ezpublish-kernel/pull/2862. Please refer to it for more information.

EZP-31113: Configured Slot for AssignSectionToSubtreeSignal

---

lib/Indexer.php

Jira: https://jira.ez.no/browse/EZP-30664
Target version: 1.5 (_eZ Platform 1.7+)_
Continue to index other content in the iteration when an exception happens.

EZP-30664: Skipped indexing erroneous Content and logged all exceptions

---

lib/CoreFilter/NativeCoreFilter.php

| **JIRA issue**     | [EZP-31299](https://jira.ez.no/browse/EZP-31299)
| **Bug**| no
| **New feature**    | yes
| **Target version** | `1.7` and higher
| **Doc needed** | no
Added new option to language settings `excludeTranslationsFromAlwaysAvailable` for "useAlwaysAvailable" working change (default set to true; if false - the always available will do not exclude all translations by given languages, but only exclude main translation by given languages)

EZP-31299: Changed condition for "useAlwaysAvailable"

---

lib/FieldMapper/ContentFieldMapper/BlockDocumentsBaseContentFields.php
lib/Query/Common/CriterionVisitor/ObjectStateIdentifierIn.php
lib/Query/Common/CriterionVisitor/SectionIdentifierIn.php
lib/Resources/config/container/solr/criterion_visitors.yml

> JIRA: https://jira.ez.no/browse/EZP-31080
Implemented visitors for new criterions:
* ObjectStateIdentifier
* SectionIdentifier
I wanted to add more visitors but it isn't that easy. All user based criterions will require creating new document type so it's out of scope for now.

EZP-31080: Created missing search Criterions

---

lib/Query/Common/CriterionVisitor/AggregateCriterion.php
lib/Query/Common/CriterionVisitor/CompositeCriterion.php
lib/Resources/config/container/solr/criterion_visitors.yml

| **JIRA issue**     | [EZP-31415](https://jira.ez.no/browse/EZP-31415)
| **Requires** | https://github.com/ezsystems/ezpublish-kernel/pull/2958 |
| **Bug/Improvement**| no
| **New feature**    | yes
| **Target version** | `master`
| **Tests pass**     | yes
| **Doc needed**     | yes
Impl. criterion visitor for `eZ\Publish\API\Repository\Values\Content\Query\Criterion\CompositeCriterion`. See https://github.com/ezsystems/ezpublish-kernel/pull/2958
**TODO**:

EZP-31415: Impl. criterion visitor for CompositeCriterion

---

lib/Query/Common/CriterionVisitor/SectionIdentifierIn.php

> JIRA: https://jira.ez.no/browse/EZP-31080
`SectionIdentifier` criterion can accept a string or an array of strings. It was passing strings directly to `array_map` which resulted in error. This casts strings to single element array which solves the problem.

EZP-31080: Fixed SectionIdentifier criterion to handle strings

---

.travis.yml
README.md
composer.json
lib/Query/Common/FacetBuilderVisitor/Aggregate.php
tests/bootstrap.php

| **JIRA issue**                          | [EZP-31007](https://jira.ez.no/browse/EZP-31007)
| **Type**                                   | improvement
| **Target eZ Platform version** | `v3.0.0`
| **BC breaks**                          | no
| **Tests pass**                          | yes
| **Doc needed**                       | no
This PR replaces `ezpublish-kernel` references with `ezplatform-kernel` in `composer.json` and other places and fixes dependency issues blocking package installation (due to Composer minimum stability requirements):
- `ezsystems/doctrine-dbal-schema:^1.0@dev` is required  by `ezplatform-kernel:^1.0@dev`.

EZP-31007: Replaced ezpublish-kernel with ezplatform-kernel

---

lib/Indexer.php
lib/Resources/config/container/solr.yml

| **JIRA issue**                          | [EZP-31517](https://jira.ez.no/browse/EZP-31517) blocking [EZP-30921](https://jira.ez.no/browse/EZP-30921)
| **Requires**                        | ezsystems/ezplatform-kernel#10
| **Type**                                   | improvement
| **Target eZ Platform version** | `v3.0`
| **BC breaks**                          | yes
| **Tests pass**                          | yes
| **Doc needed**                       | yes
This PR refactors Solr Search Indexer to rely on Doctrine Connection instead of Database Handler from Zeta Components (see ezsystems/ezplatform-kernel#10 for more details).
Additionally this Indexer code also relied on …

EZP-31517: Refactored Indexer to rely on Doctrine\DBAL

---

bin/.travis/init_solr.sh

I was running tests for https://github.com/ezsystems/ezplatform-xmltext-fieldtype on my local, where I have multiple Solr instances. After executing `./vendor/ezsystems/ezplatform-solr-search-engine/bin/.travis/init_solr.sh` cores were created in wrong Solr instance.
This PR fixes it.

Specify port in solr_create_core for the tests

---

tests/lib/SetupFactory/LegacySetupFactory.php

| **JIRA issue**                          | [EZP-31423](https://jira.ez.no/browse/EZP-31423) blocking [EZP-30921](https://jira.ez.no/browse/EZP-30921)
| **Type**                                   | improvement
| **Target eZ Platform version** | `v3.0`
| **BC breaks**                          | no
| **Tests pass**                          | yes
| **Doc needed**                       | no
This PR refactors test SetupFactory to stop relying on Database Handler from Zeta Components in favor of Doctrine Connection.
I've optimized loading a list of Content items to be indexed.
I've also refactored `getTestConfigurationFile` method simply because I couldn't look at it.

EZP-31423: Refactored SetupFactory to rely on Doctrine Connection

---

lib/Handler.php
lib/Slot/RemoveTranslation.php
tests/lib/Slot/RemoveTranslationTest.php

| **JIRA issue**     | [EZP-31420](https://jira.ez.no/browse/EZP-31420)
| **New feature**    | no
| **Target version** | `1,7`
| **Tests pass**     | [yes](https://travis-ci.org/github/ezsystems/ezpublish-kernel/builds/675704022)
| **Doc needed**     | no
Depends on: https://github.com/ezsystems/ezpublish-kernel/pull/3013
Removing a content translation does not remove the associated SolR documents
**TODO**:

EZP-31420: Deleted translation from Solr when deleted from Version

---

.travis.yml
bin/.travis/init_solr.sh
tests/lib/Resources/config/multicore_dedicated.yml

Target branch: `1.7`, `2.0`, `3.0`, `master`, for **fast-forward** merge as it contains #182 
This PR fixes outstanding issue with Solr/Kernel [integration test failing](https://travis-ci.org/github/ezsystems/ezplatform-solr-search-engine/jobs/683846982#L988) when using Solr with dedicated cores setup (core per language).
**For review**: ed483bb - added `core5` and mapped it to `pol-PL`
Alternatively I could change `\eZ\Publish\API\Repository\Tests\LocationServiceTest::testSwapLocationForContentWithCustomUrlAliases` not to use `pol-PL`.

[Solr Bundle v1.7] Fixed CI issues & enabled Slack notifications

---

composer.json

Looks like we're running tests using unmaintained Kernel 7.4.4 instead of 6.13.x intended for eZ Platform 1.13. 
Solr Bundle v1.5 was intended to [support eZ Platform 1.7, 1.13 and anything older than 2.5](https://github.com/ezsystems/ezplatform-solr-search-engine/blob/v1.7.3/README.md).  Currently we still maintain eZ Platform 1.13 LTS only, so other versions constraint can be dropped.
**TODO**

[Solr Bundle 1.5] Forced Kernel 6.13

---

composer.json
lib/FieldMapper/ContentFieldMapper/BlockDocumentsBaseContentFields.php
lib/FieldMapper/ContentFieldMapper/ContentDocumentLocationFields.php
lib/FieldMapper/LocationFieldMapper/LocationDocumentBaseFields.php
lib/Handler.php

| **JIRA issue**     | [EZP-25484](https://jira.ez.no/browse/EZP-25484), follow up to [EZP-31420](https://jira.ez.no/browse/EZP-31420) (#173)
| **Required by** | ezsystems/ezpublish-kernel#3034
| **Target eZ Platform version** | 2.5.x, 3.x
| **BC breaks**      | yes, on indexed remote ID values
| **Tests pass**     | [yes](https://travis-ci.org/github/ezsystems/ezplatform-solr-search-engine/builds/689259741)
| **Doc needed**     | yes, but due to Kernel changes (see Kernel PR)
This PR changes the way Content & Location remote IDs are indexed by allowing almost all possible input which is consistent with Content/Location API.
So now you're able to index in Solr Content items with such remote …

[Fast-forward merge] Improved indexing of Identifiers

---

.travis.yml

| **JIRA issue**                          | Follow-up to #185, blocking [EZP-31325](https://jira.ez.no/browse/EZP-31325)
| **Type**                                   | bug
| **Solr Bundle version**            | `1.5` only
When resolving #185 I missed the fact that `.travis.yml` enforced `ezpublish-kernel:6.7` (which is past EOM) for some jobs. The jobs are still valid as they test different setups, but should be executed with a Kernel version from composer.

[Travis] Dropped testing using Kernel 6.7

---

.travis.yml
bin/.travis/init_solr.sh

> JIRA: - 
Enabled Solr testing on 7.7.3 (last 7.X release) and 8.5.2

Run integration tests on Solr 7.7.3 and 8.5.2

---

lib/Query/Location/SortClauseVisitor/Location/Visibility.php

\> JIRA: \[EZEE-3208\](https://jira.ez.no/browse/EZEE-3208)
\### Description
Aligned \`\\eZ\\Publish\\API\\Repository\\Values\\Content\\Query\\SortClause\\Location\\Visibility\` behaviour to legacy search engine. See https://github.com/ezsystems/ezplatform-kernel/blob/9f59de2eb64de9cf447f07edca43ed1f91dea065/eZ/Publish/Core/Persistence/Legacy/Filter/SortClauseQueryBuilder/Location/VisibilityQueryBuilder.php#L23
\## Checklist
\- \[X\] Code follows the code style of this project (use \`$ composer fix-cs\`).  
\- \[ \] Change requires a change to the documentation.  
\- \[X\] Code is ready for a review.

EZEE-3208: Visibility SortClause ignores content visibility

---

lib/Resources/config/container/solr.yml

> JIRA: https://jira.ez.no/browse/EZP-31588
Replaced deprecated `ezpublish.searchEngine` and `ezpublish.searchEngineIndexer` tags in favour of `ezplatform.search_engine` and `ezplatform.search_engine.indexer`
:exclamation: **Requires ezsystems/ezplatform-kernel#51** :exclamation:

EZP-31588: Replaced deprecated ezpublish.searchEngine and ezpublish.searchEngineIndexer tags

---

composer.json
lib/FieldMapper/ContentFieldMapper/BlockDocumentsBaseContentFields.php
lib/FieldMapper/LocationFieldMapper/LocationDocumentBaseFields.php
lib/Query/Common/SortClauseVisitor/ContentId.php
lib/Query/Location/SortClauseVisitor/Location/Id.php

| | |
| --- | --- |
| **JIRA issue** | [EZP-31325](https://jira.ez.no/browse/EZP-31325)
| **Requires for tests** | ezsystems/ezpublish-kernel#3029
| **Type** | bug
| **Solr version** | 4.10+
| **Solr Bundle version** | `1.5`, `1.7`, `2.0`, 3.0+`
| **eZ Platform version** | `v1.13+`
| **Tests** | [passing](https://travis-ci.org/github/ezsystems/ezplatform-solr-search-engine/builds/692518141) with ezsystems/ezpublish-kernel#3029
| **Doc needed** | no
Solr Fields `location_id` and `content_id` are indexed as `identifier`s which are strings by default. This causes dictionary (alphabetical) ordering of IDs when sorting. Those IDs, in fact, are numbers and numerical sorting should be applied.
The bug exists for an edge case when the IDs have different string length, e.g. "9" and "10". For the …

EZP-31325: Fixed sorting by Content & Location ID

---

lib/FieldMapper/ContentFieldMapper/BlockDocumentsBaseContentFields.php

> JIRA:\[EZP-32001](https://jira.ez.no/browse/EZP-32001)
Skipped empty object state groups during indexing.

EZP-32001: Skipped empty object state groups during indexing

---

lib/Handler.php

> JIRA: https://jira.ez.no/browse/EZP-31741
Part of the ezsystems/ezplatform-kernel#113

EZP-31741: Fixed features detection in eZ\Publish\Core\Repository\SearchService::supports

---

lib/Handler.php

> JIRA: https://jira.ez.no/browse/EZP-27458
Follow up for https://github.com/ezsystems/ezplatform-solr-search-engine/pull/192. Method `\EzSystems\EzPlatformSolrSearchEngine\Handler::supports` called with `SearchService::CAPABILITY_AGGREGATIONS` as an argument should return `true`. 
Issue reported by @mnocon as result of QA process.

EZP-27458: Fixed detection of aggregations capability in EzSystems\EzPlatformSolrSearchEngine\Handler::supports

---

lib/ResultExtractor/AggregationResultExtractor/RangeAggregationResultExtractor.php

> JIRA: https://jira.ez.no/browse/EZP-27458
In non-single core setup order of range aggregation results are not guaranteed (see failing build  https://travis-ci.org/github/ezsystems/ezplatform-solr-search-engine/jobs/736166712). 
This PR ensures that entries in \`\\eZ\\Publish\\API\\Repository\\Values\\Content\\Search\\AggregationResult\\RangeAggregationResult\` are in the exact same order as they ware defined in \`eZ\\Publish\\API\\Repository\\Values\\Content\\Query\\Aggregation\\AbstractRangeAggregation\`.

EZP-27458: Ensured that Range Aggregation results keeps user defined order

---

lib/Query/Common/AggregationVisitor/AbstractStatsAggregationVisitor.php
tests/lib/Search/Query/Common/AggregationVisitor/StatsAggregationVisitorTest.php

> JIRA: EZP-27458
Currently stats aggregation while computing count value take into account all examined documents instead of limit documents to those with really influence result. 
In other words we expect that result avg(filed) = sum(field) / count(field). Issue detected by https://travis-ci.com/github/ezsystems/ezplatform-kernel/jobs/407011420 (ezsystems/ezplatform-kernel#129)

EZP-27458: Limited stats aggregation to documents which contain aggregation target field

---

lib/Query/Common/SortClauseVisitor/CustomField.php
lib/Resources/config/container/solr/sort_clause_visitors.yml

> JIRA: [EZP-32108](https://jira.ez.no/browse/EZP-32108)
Impl. visitor for https://github.com/ezsystems/ezplatform-kernel/pull/135

EZP-32108: Added CustomField sort clause

---

lib/ResultExtractor/LoadingResultExtractor.php

> JIRA: -
Fixed constructor in `\EzSystems\EzPlatformSolrSearchEngine\ResultExtractor\LoadingResultExtractor`. 
Note to reviewers: `\EzSystems\EzPlatformSolrSearchEngine\ResultExtractor\LoadingResultExtractor` class is not used however source code should be  valid.

Fixed constructor in LoadingResultExtractor

---

lib/ResultExtractor.php

> JIRA: -
Refactored `\EzSystems\EzPlatformSolrSearchEngine\ResultExtractor::extract` method by splitting it into several smaller methods. 
The main reason behind this PR is to simplify result extractor decoration in order to  to to be able to enrich search hits with custom metadata e.g. https://lucene.apache.org/solr/guide/7_3/spatial-search.html#SpatialSearch-geodist 
Next step in refactoring for 4.x is to extract SearchHit mapping logic  to dedicated ResutiHitExtractor service.

Refactored ResultExtractor::extract method

---

tests/lib/Resources/config/cloud.yml
tests/lib/Resources/config/multicore_dedicated.yml
tests/lib/Resources/config/multicore_shared.yml
tests/lib/Resources/config/single_core.yml

| **JIRA issue**                          | Related to [IBX-872](https://issues.ibexa.co/browse/IBX-872)
| **Related to**                           | ezsystems/ezplatform-kernel#223
| **Type**                                   | bug
| **Target Ibexa version** | `v3.3`+
| **BC breaks**                          | no
| **Doc needed**                       | no
Dropped unused searchable overrides for Float, Media, Image, and Url Field Types. They were overridden by `.class` parameters which were dropped for 3.0 via ezsystems/ezpublish-kernel#2911. The related classes were just dropped via  ezsystems/ezplatform-kernel#223 as they're not used anywhere.
The issue needs to be …

[Tests] Dropped unused searchable Field Types overrides

---

lib/Resources/config/container/solr/aggregation_result_extractors.yml

This explicitly set the inner service so autowiring does not fail on symfony 5.2.7

IBX-942: Add missing inner service argument

---

lib/Resources/config/container/solr/aggregation_result_extractors.yml

Jira issue: [IBX-942](https://issues.ibexa.co/browse/IBX-942)
This is a backport of https://github.com/ezsystems/ezplatform-solr-search-engine/pull/217 that will most likely resolve failing tests in `ezplatform-richtext` bundle on branch 2.3. An example failing build: https://app.travis-ci.com/github/ezsystems/ezplatform-richtext/jobs/539330206#L1540.

IBX-942: [Backport] Added missing inner service argument
